added links of previous year team ans then created page for team 2021-22
abhishekshree/spo-website pull request #22
Opened 2022-04-18 07:13 UTC by amdpt323

2022-04-18 08:15 UTC, abhishekshree commented
The links don't look aesthetic as of now; make them look similar to the ones on the `students` page (for resources).

The folder stricture should be `student-team/2021-22.tsx` to get a route like `/student-team/2021-22`

2022-04-18 08:17 UTC, abhishekshree commented on pages/student-team.tsx
> +      <Container>
Change link to ones on the students page

2022-04-18 08:17 UTC, abhishekshree requested changes
Put it in the student-team folder, rename it to just the academic year.

2022-04-18 11:06 UTC, 1-Harshit commented
- for #6

2022-04-19 10:06 UTC, 1-Harshit commented
@amdpt323 
Fix the the font size
![image](https://user-images.githubusercontent.com/75195728/163980835-8aabf9a1-5bb1-4e77-b30d-d926068f7774.png)

2022-04-19 10:08 UTC, 1-Harshit commented
- duplicate of #34

2022-04-19 10:08 UTC, closed without merging